
import {Answer} from './Answer.js'

export const subjects = [

  {id: 16, date: new Date("2021-09-26"), name: "Löhne entlasten, Kapital gerecht besteuern"},
  {id: 15, date: new Date("2021-09-26"), name: "Ehe für Alle"},

  {id: 14, date: new Date("2021-06-13"), name: "Anti-Terror-Gesetz", outcome: Answer.Yes},
  {id: 13, date: new Date("2021-06-13"), name: "Trinkwasser-Initiative", outcome: Answer.No},
  {id: 12, date: new Date("2021-06-13"), name: "Pestizid-Initiative", outcome: Answer.No},
  {id: 11, date: new Date("2021-06-13"), name: "Covid-Gesetz", outcome: Answer.Yes},
  {id: 10, date: new Date("2021-06-13"), name: "CO2-Gesetz", outcome: Answer.No},

  {id: 9, date: new Date("2021-03-07"), name: "Ja zum Verhüllungsverbot", outcome: Answer.Yes},
  {id: 8, date: new Date("2021-03-07"), name: "E-ID Gesetz", outcome: Answer.No},
  {id: 7, date: new Date("2021-03-07"), name: "Wirtschaftspartnerschaftsabkommen Indonesien", outcome: Answer.Yes},

  {id: 6, date: new Date("2020-11-29"), name: "Kriegsgeschäfte-Initiative", outcome: Answer.No},
  {id: 5, date: new Date("2020-11-29"), name: "Konzernverantwortungs-Initiative", outcome: Answer.No},

  {id: 4, date: new Date("2020-09-27"), name: "Kinderzulagen", outcome: Answer.No},
  {id: 3, date: new Date("2020-09-27"), name: "Vaterschaftsurlaub", outcome: Answer.Yes},
  {id: 2, date: new Date("2020-09-27"), name: "Jagdgesetz (Wolf)", outcome: Answer.No},
  {id: 1, date: new Date("2020-09-27"), name: "Kampfjetbeschaffung", outcome: Answer.Yes},
  {id: 0, date: new Date("2020-09-27"), name: "Begrenzungsinitiative", outcome: Answer.No},
];

export const parties = [
  {
    id: 0,
    name: "SP",
    votes: [
      {id: 0, answer: Answer.No},
      {id: 1, answer: Answer.No},
      {id: 2, answer: Answer.No},
      {id: 3, answer: Answer.Yes},
      {id: 4, answer: Answer.No},
      {id: 5, answer: Answer.Yes},
      {id: 6, answer: Answer.Yes},
      {id: 7, answer: Answer.No},
      {id: 8, answer: Answer.No},
      {id: 9, answer: Answer.No},
      {id: 10, answer: Answer.Yes},
      {id: 11, answer: Answer.Yes},
      {id: 12, answer: Answer.Yes},
      {id: 13, answer: Answer.Yes},
      {id: 14, answer: Answer.No},
      {id: 15, answer: Answer.Yes},
      {id: 16, answer: Answer.Yes},
    ]
  },{
    id: 1,
    name: "GP",
    votes: [
      {id: 0, answer: Answer.No},
      {id: 1, answer: Answer.No},
      {id: 2, answer: Answer.No},
      {id: 3, answer: Answer.Yes},
      {id: 4, answer: Answer.No},
      {id: 5, answer: Answer.Yes},
      {id: 6, answer: Answer.Yes},
      {id: 7, answer: Answer.No},
      {id: 8, answer: Answer.No},
      {id: 9, answer: Answer.No},
      {id: 10, answer: Answer.Yes},
      {id: 11, answer: Answer.Yes},
      {id: 12, answer: Answer.Yes},
      {id: 13, answer: Answer.Yes},
      {id: 14, answer: Answer.No},
      {id: 15, answer: Answer.Yes},
      {id: 16, answer: Answer.Yes},
    ]
  },{
    id: 2,
    name: "GLP",
    votes: [
      {id: 0, answer: Answer.No},
      {id: 1, answer: Answer.Yes},
      {id: 2, answer: Answer.No},
      {id: 3, answer: Answer.Yes},
      {id: 4, answer: Answer.No},
      {id: 5, answer: Answer.Yes},
      {id: 6, answer: Answer.No},
      {id: 7, answer: Answer.Yes},
      {id: 8, answer: Answer.No},
      {id: 9, answer: Answer.No},
      {id: 10, answer: Answer.Yes},
      {id: 11, answer: Answer.Yes},
      {id: 12, answer: Answer.Abstention},
      {id: 13, answer: Answer.Yes},
      {id: 14, answer: Answer.No},
      {id: 15, answer: Answer.Yes},
      {id: 16, answer: Answer.No},
    ]
  },{
  //   id: 3,
  //   name: "EVP",
  //   votes: [
  //     {id: 0, answer: Answer.No},
  //     {id: 1, answer: Answer.Yes},
  //     {id: 2, answer: Answer.No},
  //     {id: 3, answer: Answer.Yes},
  //     {id: 4, answer: Answer.Yes},
  //     {id: 5, answer: Answer.Yes},
  //     {id: 6, answer: Answer.Yes},
  //     {id: 7, answer: Answer.No},
  //     {id: 8, answer: Answer.Yes},
  //     {id: 9, answer: Answer.Abstention},
  //     {id: 10, answer: Answer.Yes},
  //     {id: 11, answer: Answer.Yes},
  //     {id: 12, answer: Answer.Yes},
  //     {id: 13, answer: Answer.Yes},
  //     {id: 14, answer: Answer.Yes},
  //     {id: 15, answer: Answer.No},
  //     {id: 16, answer: Answer.Yes},
  //   ]
  // },{
  //   id: 4,
  //   name: "BDP",
  //   votes: [
  //     {id: 0, answer: Answer.No},
  //     {id: 1, answer: Answer.Yes},
  //     {id: 2, answer: Answer.Yes},
  //     {id: 3, answer: Answer.Yes},
  //     {id: 4, answer: Answer.Yes},
  //     {id: 5, answer: Answer.Yes},
  //     {id: 6, answer: Answer.No},
  //     {id: 7, answer: Answer.Novote},
  //     {id: 8, answer: Answer.Novote},
  //     {id: 9, answer: Answer.Novote},
  //     {id: 10, answer: Answer.Novote},
  //     {id: 11, answer: Answer.Novote},
  //     {id: 12, answer: Answer.Novote},
  //     {id: 13, answer: Answer.Novote},
  //     {id: 14, answer: Answer.Novote},
  //   ]
  // },{
    id: 5,
    name: "CVP",
    votes: [
      {id: 0, answer: Answer.No},
      {id: 1, answer: Answer.Yes},
      {id: 2, answer: Answer.Yes},
      {id: 3, answer: Answer.Yes},
      {id: 4, answer: Answer.Yes},
      {id: 5, answer: Answer.No},
      {id: 6, answer: Answer.No},
      {id: 7, answer: Answer.Yes},
      {id: 8, answer: Answer.Yes},
      {id: 9, answer: Answer.No},
      {id: 10, answer: Answer.Yes},
      {id: 11, answer: Answer.Yes},
      {id: 12, answer: Answer.No},
      {id: 13, answer: Answer.No},
      {id: 14, answer: Answer.Yes},
      {id: 15, answer: Answer.Yes}, // why not on website?
      {id: 16, answer: Answer.No},
    ]
  },{
    id: 6,
    name: "FDP",
    votes: [
      {id: 0, answer: Answer.No},
      {id: 1, answer: Answer.Yes},
      {id: 2, answer: Answer.Yes},
      {id: 3, answer: Answer.No},
      {id: 4, answer: Answer.Yes},
      {id: 5, answer: Answer.No},
      {id: 6, answer: Answer.No},
      {id: 7, answer: Answer.Yes},
      {id: 8, answer: Answer.Yes},
      {id: 9, answer: Answer.No},
      {id: 10, answer: Answer.Yes},
      {id: 11, answer: Answer.Yes},
      {id: 12, answer: Answer.No},
      {id: 13, answer: Answer.No},
      {id: 14, answer: Answer.Yes},
      {id: 15, answer: Answer.Yes},
      {id: 16, answer: Answer.No},
    ]
  },{
  //   id: 6,
  //   name: "EDU",
  //   votes: [
  //     {id: 0, answer: Answer.Novote},
  //     {id: 1, answer: Answer.Novote},
  //     {id: 2, answer: Answer.Novote},
  //     {id: 3, answer: Answer.Novote},
  //     {id: 4, answer: Answer.Novote},
  //     {id: 5, answer: Answer.Novote},
  //     {id: 6, answer: Answer.Novote},
  //     {id: 7, answer: Answer.Yes},
  //     {id: 8, answer: Answer.No},
  //     {id: 9, answer: Answer.Yes},
  //     {id: 10, answer: Answer.No},
  //     {id: 11, answer: Answer.No},
  //     {id: 12, answer: Answer.No},
  //     {id: 13, answer: Answer.No},
  //     {id: 14, answer: Answer.Abstention},
  //     {id: 15, answer: Answer.No},
  //     {id: 16, answer: Answer.No},
  //   ]
  // },{
    id: 8,
    name: "SVP",
    votes: [
      {id: 0, answer: Answer.Yes},
      {id: 1, answer: Answer.Yes},
      {id: 2, answer: Answer.Yes},
      {id: 3, answer: Answer.No},
      {id: 4, answer: Answer.Yes},
      {id: 5, answer: Answer.No},
      {id: 6, answer: Answer.No},
      {id: 7, answer: Answer.Yes},
      {id: 8, answer: Answer.Yes},
      {id: 9, answer: Answer.Yes},
      {id: 10, answer: Answer.No},
      {id: 11, answer: Answer.Abstention},
      {id: 12, answer: Answer.No},
      {id: 13, answer: Answer.No},
      {id: 14, answer: Answer.Yes},
      {id: 15, answer: Answer.No},
      {id: 16, answer: Answer.No},
    ]
  },
];
