
import { Answer } from './Answer.js'

export const terms = [
  {
    id: 52,
    hash: "2023_27",
    end_date: new Date("2027-12-02"),
    start_date: new Date("2023-12-04"),
    parties: [
      { id: 0, name: "SP" },
      { id: 1, name: "GP" },
      { id: 2, name: "GLP" },
      { id: 3, name: "CVP" },
      { id: 4, name: "FDP" },
      { id: 5, name: "SVP" },
    ],
    subjects: [],
  },
  {
    id: 50,
    hash: "2015_19",
    start_date: new Date("2015-12-03"),
    end_date: new Date("2019-12-01"),
    parties: [
      { id: 0, name: "SP" },
      { id: 1, name: "GP" },
      { id: 2, name: "GLP" },
      { id: 3, name: "CVP" },
      { id: 4, name: "FDP" },
      { id: 5, name: "SVP" },
    ],
    subjects: [
      {
        id: 628, 
        date: new Date("2019-05-19"), 
        name: "EU-Waffenrichtlinie", 
        hash: "2019-05_628",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 627, 
        date: new Date("2019-05-19"), 
        name: "Steuerreform und AHV (STAF)", 
        hash: "2019-05_627",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Abstention },
        ],
      },
      {
        id: 626, 
        date: new Date("2019-02-10"), 
        name: "Zersiedlungsinitiative", 
        hash: "2019-02_626",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 625, 
        date: new Date("2018-11-25"), 
        name: "Überwachung von Versicherten", 
        hash: "2018-11_625",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 624, 
        date: new Date("2018-11-25"), 
        name: "Selbstbestimmungsinitiative", 
        hash: "2018-11_624",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 623,
        date: new Date("2018-11-25"),
        name: "Hornkuh-Initiative",
        hash: "2018-11_623",
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ]
      },
    ],
  },
  {
    id: 51,
    hash: "2019_23",
    start_date: new Date("2019-12-02"),
    end_date: new Date("2023-12-03"),
    parties: [
      { id: 0, name: "SP" },
      { id: 1, name: "GP" },
      { id: 2, name: "GLP" },
      { id: 3, name: "CVP" },
      { id: 4, name: "FDP" },
      { id: 5, name: "SVP" },
    ],
    subjects: [
      {
        id: 661,
        date: new Date("2022-09-25"),
        name: "Verrechnungssteuer",
        hash: "2022-09_661",
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ]
      },
      {
        id: 660,
        date: new Date("2022-09-25"),
        name: "Stabilisierung AHV (Rentenalter)",
        hash: "2022-09_660",
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ]
      },
      {
        id: 659,
        date: new Date("2022-09-25"),
        name: "Stabilisierung AHV (MWST)",
        hash: "2022-09_659",
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ]
      },
      {
        id: 658,
        date: new Date("2022-09-25"),
        name: "Massentierhaltungsinitiative",
        hash: "2022-09_658",
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Abstention },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ]
      },
      {
        id: 657, 
        date: new Date("2022-05-15"), 
        name: "Frontex EU-Verordnung", 
        hash: "2022-05_657", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 656, 
        date: new Date("2022-05-15"), 
        name: "Änderung des Transplantationsgesetzes", 
        hash: "2022-05_656", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 655, 
        date: new Date("2022-05-15"), 
        name: "Änderung des Filmgesetzes", 
        hash: "2022-05_655", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 654, 
        date: new Date("2022-02-13"), 
        name: "Massnahmenpaket zugunsten der Medien", 
        hash: "2022-02_654", 
        outcome: Answer.No,
        parties: [
          // https://www.srf.ch/news/abstimmungen-13-februar-2022/massnahmenpaket-medien/abstimmung-vom-13-februar-parolenspiegel-zum-massnahmenpaket-zugunsten-der-medien
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 653, 
        date: new Date("2022-02-13"), 
        name: "Änderung Bundesgesetzes Stempelabgaben", 
        hash: "2022-02_653", 
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 652, 
        date: new Date("2022-02-13"), 
        name: "Kinder ohne Tabakwerbung", 
        hash: "2022-02_652", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.No },
        ]
      },
      {
        id: 651, 
        date: new Date("2022-02-13"), 
        name: "Tierversuchsverbotsinitiative", 
        hash: "2022-02_651", 
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 650, 
        date: new Date("2021-11-28"), 
        name: "Covid-19-Gesetz #2", 
        hash: "2021-11_650", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 649, 
        date: new Date("2021-11-28"), 
        name: "Justiz-Initiative", 
        hash: "2021-11_649", 
        outcome: Answer.No,
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 648, 
        date: new Date("2021-11-28"), 
        name: "Pflegeinitiative", 
        hash: "2021-11_648", 
        outcome: Answer.Yes,
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Abstention },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 647, 
        date: new Date("2021-09-26"), 
        name: "Ehe für Alle", 
        outcome: Answer.Yes, 
        hash: "2021-09_647",
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 646, 
        date: new Date("2021-09-26"), 
        name: "Löhne entlasten, Kapital gerecht besteuern", 
        hash: "2021-09_646",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 645, 
        date: new Date("2021-06-13"), 
        name: "Anti-Terror-Gesetz", 
        hash: "2021-06_645",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Abstention },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 644, 
        date: new Date("2021-06-13"), 
        name: "CO2-Gesetz", 
        hash: "2021-06_644",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 643, 
        date: new Date("2021-06-13"), 
        name: "Covid-19-Gesetz #1", 
        hash: "2021-06_643",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.Abstention },
        ],
      },
      {
        id: 642, 
        date: new Date("2021-06-13"), 
        name: "Pestizid-Initiative", 
        hash: "2021-06_642",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Abstention },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 641, 
        date: new Date("2021-06-13"), 
        name: "Trinkwasser-Initiative", 
        hash: "2021-06_641",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 640, 
        date: new Date("2021-03-07"), 
        name: "Freihandelsabkommen Indonesien", 
        hash: "2021-03_640",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 639, 
        date: new Date("2021-03-07"), 
        name: "E-ID Gesetz", 
        hash: "2021-03_639",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 638, 
        date: new Date("2021-03-07"), 
        name: "Verhüllungsverbot", 
        hash: "2021-03_638",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Abstention },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 637, 
        date: new Date("2020-11-29"), 
        name: "Kriegsgeschäfte-Initiative", 
        hash: "2020-11_637",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 636, 
        date: new Date("2020-11-29"), 
        name: "Konzernverantwortungsinitiative", 
        hash: "2020-11_636",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 635, 
        date: new Date("2020-09-27"), 
        name: "Kampfjetbeschaffung", 
        hash: "2020-09_635",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 634, 
        date: new Date("2020-09-27"), 
        name: "Vaterschaftsurlaub", 
        hash: "2020-09_634",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 633, 
        date: new Date("2020-09-27"), 
        name: "Kinderzulagen", 
        hash: "2020-09_633",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Yes },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 632, 
        date: new Date("2020-09-27"), 
        name: "Jagdgesetz (Wolf)", 
        hash: "2020-09_632",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 631, 
        date: new Date("2020-09-27"), 
        name: "Begrenzungsinitiative", 
        hash: "2020-09_631",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.No },
          { id: "GP", answer: Answer.No },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.Yes },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.Yes },
        ],
      },
      {
        id: 630, 
        date: new Date("2020-02-09"), 
        name: "Sexuelle Diskriminierung", 
        hash: "2020-02_630",
        outcome: Answer.Yes, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.Yes },
          { id: "CVP", answer: Answer.Yes },
          // { id:"EVP", answer: Answer.Abstention },
          { id: "FDP", answer: Answer.Yes },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.Yes },
          { id: "SVP", answer: Answer.No },
        ],
      },
      {
        id: 629, 
        date: new Date("2020-02-09"), 
        name: "Mehr bezahlbare Wohnungen", 
        hash: "2020-02_629",
        outcome: Answer.No, 
        parties: [
          { id: "SP", answer: Answer.Yes },
          { id: "GP", answer: Answer.Yes },
          { id: "GLP", answer: Answer.No },
          { id: "CVP", answer: Answer.No },
          // { id:"EVP", answer: Answer.No },
          { id: "FDP", answer: Answer.No },
          // { id:"EDU", answer: Answer.No },
          // { id:"BDP", answer: Answer.No },
          { id: "SVP", answer: Answer.No },
        ],
      },
    ]
  }
];

// export const parties = [
//   {id: 0, name: "SP"},
//   {id: 1, name: "GP"},
//   {id: 2, name: "GLP"},
//   {id: 3, name: "CVP"},
//   {id: 4, name: "FDP"},
//   {id: 5, name: "SVP"},
// ]

// export const parties = [
//   {
//     id: 0,
//     name: "SP",
//     votes: [
//       {id: 631, answer: Answer.No},
//       {id: 632, answer: Answer.No},
//       {id: 633, answer: Answer.No},
//       {id: 634, answer: Answer.Yes},
//       {id: 635, answer: Answer.No},
//       {id: 636, answer: Answer.Yes},
//       {id: 637, answer: Answer.Yes},
//       {id: 638, answer: Answer.No},
//       {id: 639, answer: Answer.No},
//       {id: 640, answer: Answer.No},
//       {id: 641, answer: Answer.Yes},
//       {id: 642, answer: Answer.Yes},
//       {id: 643, answer: Answer.Yes},
//       {id: 644, answer: Answer.Yes},
//       {id: 645, answer: Answer.No},
//       {id: 646, answer: Answer.Yes},
//       {id: 647, answer: Answer.Yes},
//       {id: 648, answer: Answer.No},
//       {id: 649, answer: Answer.Yes},
//       {id: 650, answer: Answer.Yes},
//       {id: 651, answer: Answer.No},
//       {id: 652, answer: Answer.Yes},
//       {id: 653, answer: Answer.No},
//       {id: 654, answer: Answer.Yes},
//       {id: 655, answer: Answer.Yes},

//       {id: 111, answer: Answer.Yes},
//       {id: 222, answer: Answer.No},
//       {id: 333, answer: Answer.No},
//       {id: 444, answer: Answer.No},
//     ]
//   },{
//     id: 1,
//     name: "GP",
//     votes: [
//       {id: 631, answer: Answer.No},
//       {id: 635, answer: Answer.No},
//       {id: 632, answer: Answer.No},
//       {id: 634, answer: Answer.Yes},
//       {id: 633, answer: Answer.No},
//       {id: 636, answer: Answer.Yes},
//       {id: 637, answer: Answer.Yes},
//       {id: 640, answer: Answer.No},
//       {id: 639, answer: Answer.No},
//       {id: 638, answer: Answer.No},
//       {id: 644, answer: Answer.Yes},
//       {id: 643, answer: Answer.Yes},
//       {id: 642, answer: Answer.Yes},
//       {id: 641, answer: Answer.Yes},
//       {id: 645, answer: Answer.No},
//       {id: 647, answer: Answer.Yes},
//       {id: 646, answer: Answer.Yes},

//       {id: 650, answer: Answer.Yes}, // is this right?
//       {id: 649, answer: Answer.Yes},
//       {id: 648, answer: Answer.No},

//       {id: 652, answer: Answer.Yes},
//       {id: 653, answer: Answer.No},
//       {id: 654, answer: Answer.Yes},
//       {id: 651, answer: Answer.No},

//       {id: 655, answer: Answer.Yes},


//       {id: 111, answer: Answer.Yes},
//       {id: 222, answer: Answer.No},
//       {id: 333, answer: Answer.No},
//       {id: 444, answer: Answer.No},
//     ]
//   },{
//     id: 2,
//     name: "GLP",
//     votes: [
//       {id: 631, answer: Answer.No},
//       {id: 635, answer: Answer.Yes},
//       {id: 632, answer: Answer.No},
//       {id: 634, answer: Answer.Yes},
//       {id: 633, answer: Answer.No},
//       {id: 636, answer: Answer.Yes},
//       {id: 637, answer: Answer.No},
//       {id: 640, answer: Answer.Yes},
//       {id: 639, answer: Answer.No},
//       {id: 638, answer: Answer.No},
//       {id: 644, answer: Answer.Yes},
//       {id: 643, answer: Answer.Yes},
//       {id: 642, answer: Answer.Abstention},
//       {id: 641, answer: Answer.Yes},
//       {id: 645, answer: Answer.No},
//       {id: 647, answer: Answer.Yes},
//       {id: 646, answer: Answer.No},
//       {id: 650, answer: Answer.Yes},
//       {id: 649, answer: Answer.Yes},
//       {id: 648, answer: Answer.No},
//       {id: 652, answer: Answer.Yes},
//       {id: 653, answer: Answer.Yes},
//       {id: 654, answer: Answer.Yes},
//       {id: 651, answer: Answer.No},

//       {id: 655, answer: Answer.Yes},


//       {id: 111, answer: Answer.Yes},
//       {id: 222, answer: Answer.Yes},
//       {id: 333, answer: Answer.Yes},
//       {id: 444, answer: Answer.Yes},
//     ]
//   },{
//   //   id: 3,
//   //   name: "EVP",
//   //   votes: [
//   //     {id: 631, answer: Answer.No},
//   //     {id: 635, answer: Answer.Yes},
//   //     {id: 632, answer: Answer.No},
//   //     {id: 634, answer: Answer.Yes},
//   //     {id: 633, answer: Answer.Yes},
//   //     {id: 636, answer: Answer.Yes},
//   //     {id: 637, answer: Answer.Yes},
//   //     {id: 640, answer: Answer.No},
//   //     {id: 639, answer: Answer.Yes},
//   //     {id: 638, answer: Answer.Abstention},
//   //     {id: 644, answer: Answer.Yes},
//   //     {id: 643, answer: Answer.Yes},
//   //     {id: 642, answer: Answer.Yes},
//   //     {id: 641, answer: Answer.Yes},
//   //     {id: 645, answer: Answer.Yes},
//   //     {id: 647, answer: Answer.No},
//   //     {id: 646, answer: Answer.Yes},
//   //   ]
//   // },{
//   //   id: 4,
//   //   name: "BDP",
//   //   votes: [
//   //     {id: 631, answer: Answer.No},
//   //     {id: 635, answer: Answer.Yes},
//   //     {id: 632, answer: Answer.Yes},
//   //     {id: 634, answer: Answer.Yes},
//   //     {id: 633, answer: Answer.Yes},
//   //     {id: 636, answer: Answer.Yes},
//   //     {id: 637, answer: Answer.No},
//   //     {id: 640, answer: Answer.Novote},
//   //     {id: 639, answer: Answer.Novote},
//   //     {id: 638, answer: Answer.Novote},
//   //     {id: 644, answer: Answer.Novote},
//   //     {id: 643, answer: Answer.Novote},
//   //     {id: 642, answer: Answer.Novote},
//   //     {id: 641, answer: Answer.Novote},
//   //     {id: 645, answer: Answer.Novote},
//   //   ]
//   // },{
//     id: 5,
//     name: "CVP",
//     votes: [
//       {id: 631, answer: Answer.No},
//       {id: 635, answer: Answer.Yes},
//       {id: 632, answer: Answer.Yes},
//       {id: 634, answer: Answer.Yes},
//       {id: 633, answer: Answer.Yes},
//       {id: 636, answer: Answer.No},
//       {id: 637, answer: Answer.No},
//       {id: 640, answer: Answer.Yes},
//       {id: 639, answer: Answer.Yes},
//       {id: 638, answer: Answer.No},
//       {id: 644, answer: Answer.Yes},
//       {id: 643, answer: Answer.Yes},
//       {id: 642, answer: Answer.No},
//       {id: 641, answer: Answer.No},
//       {id: 645, answer: Answer.Yes},
//       {id: 647, answer: Answer.Yes}, // why not on website?
//       {id: 646, answer: Answer.No},

//       {id: 650, answer: Answer.Yes},
//       {id: 649, answer: Answer.Abstention},
//       {id: 648, answer: Answer.No},

//       {id: 655, answer: Answer.Yes},


//       {id: 111, answer: Answer.No},
//       {id: 222, answer: Answer.Yes},
//       {id: 333, answer: Answer.Yes},
//       {id: 444, answer: Answer.Yes},
//     ]
//   },{
//     id: 6,
//     name: "FDP",
//     votes: [
//       {id: 631, answer: Answer.No},
//       {id: 635, answer: Answer.Yes},
//       {id: 632, answer: Answer.Yes},
//       {id: 634, answer: Answer.No},
//       {id: 633, answer: Answer.Yes},
//       {id: 636, answer: Answer.No},
//       {id: 637, answer: Answer.No},
//       {id: 640, answer: Answer.Yes},
//       {id: 639, answer: Answer.Yes},
//       {id: 638, answer: Answer.No},
//       {id: 644, answer: Answer.Yes},
//       {id: 643, answer: Answer.Yes},
//       {id: 642, answer: Answer.No},
//       {id: 641, answer: Answer.No},
//       {id: 645, answer: Answer.Yes},
//       {id: 647, answer: Answer.Yes},
//       {id: 646, answer: Answer.No},
//       {id: 650, answer: Answer.Yes},
//       {id: 649, answer: Answer.No},
//       {id: 648, answer: Answer.No},

//       {id: 652, answer: Answer.No},
//       {id: 653, answer: Answer.Yes},
//       {id: 654, answer: Answer.No},
//       {id: 651, answer: Answer.No},

//       {id: 655, answer: Answer.No},


//       {id: 111, answer: Answer.No},
//       {id: 222, answer: Answer.Yes},
//       {id: 333, answer: Answer.Yes},
//       {id: 444, answer: Answer.Yes},
//     ]
//   },{
//   //   id: 6,
//   //   name: "EDU",
//   //   votes: [
//   //     {id: 631, answer: Answer.Novote},
//   //     {id: 635, answer: Answer.Novote},
//   //     {id: 632, answer: Answer.Novote},
//   //     {id: 634, answer: Answer.Novote},
//   //     {id: 633, answer: Answer.Novote},
//   //     {id: 636, answer: Answer.Novote},
//   //     {id: 637, answer: Answer.Novote},
//   //     {id: 640, answer: Answer.Yes},
//   //     {id: 639, answer: Answer.No},
//   //     {id: 638, answer: Answer.Yes},
//   //     {id: 644, answer: Answer.No},
//   //     {id: 643, answer: Answer.No},
//   //     {id: 642, answer: Answer.No},
//   //     {id: 641, answer: Answer.No},
//   //     {id: 645, answer: Answer.Abstention},
//   //     {id: 647, answer: Answer.No},
//   //     {id: 646, answer: Answer.No},
//   //   ]
//   // },{
//     id: 8,
//     name: "SVP",
//     votes: [
//       {id: 631, answer: Answer.Yes},
//       {id: 635, answer: Answer.Yes},
//       {id: 632, answer: Answer.Yes},
//       {id: 634, answer: Answer.No},
//       {id: 633, answer: Answer.Yes},
//       {id: 636, answer: Answer.No},
//       {id: 637, answer: Answer.No},
//       {id: 640, answer: Answer.Yes},
//       {id: 639, answer: Answer.Yes},
//       {id: 638, answer: Answer.Yes},
//       {id: 644, answer: Answer.No},
//       {id: 643, answer: Answer.Abstention},
//       {id: 642, answer: Answer.No},
//       {id: 641, answer: Answer.No},
//       {id: 645, answer: Answer.Yes},
//       {id: 647, answer: Answer.No},
//       {id: 646, answer: Answer.No},

//       {id: 650, answer: Answer.Abstention},
//       {id: 649, answer: Answer.No},
//       {id: 648, answer: Answer.No},

//       // {id: 652, answer: Answer.No},
//       // {id: 653, answer: Answer.Yes},
//       {id: 654, answer: Answer.No},
//       // {id: 651, answer: Answer.No},
//       //
//       //
//       {id: 655, answer: Answer.No},

//       {id: 111, answer: Answer.No},
//       {id: 222, answer: Answer.Yes},
//       {id: 333, answer: Answer.Yes},
//       {id: 444, answer: Answer.Yes},
//     ]
//   },
// ];
